# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CallerID' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CallerID

  pod "PureLayout", "3.0.2"
  pod "YTKNetwork", "2.0.3"
  pod "FMDB", "2.7.2"
  pod "MBProgressHUD", "1.0.0"

end


target 'CallerID_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "FMDB", "2.7.2"

end
