# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# 共用的pod第三方
pod "FMDB", "2.7.2"

# 项目中的target各自的设置
target 'CallerID' do
 
 pod "PureLayout", "3.0.2"
 pod "YTKNetwork", "2.0.3"
 pod "MBProgressHUD", "1.0.0"
 
end

target 'CallerID_Demo' do
 
end

